# -*- coding: utf-8 -*-
"""Practica06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQDeCMYRWe_qQkDQ3hArvVeb0Ba7s5uA

# Practica 06: Ejercicios while

## 1. Contar del 1 al 10
Escribe un programa que use un ciclo `while` para imprimir los números del 1 al 10.
"""

# Escribe tu solución aquí
var1= 1
while var1 <11:
  print(var1)
  var1=var1+1

"""## 2. Pedir una contraseña hasta que sea correcta
Pide al usuario que escriba una contraseña. Mientras no escriba `python123`, el programa debe seguir preguntando.
"""

# Escribe tu solución aquí
var1=input("dame una contraseña")
while var1 !="python123":
  var1=input("dame una contraseña")

"""## 3. Sumar números mientras el usuario no escriba 0
Pide números al usuario y súmalos. El ciclo termina cuando el usuario introduce 0. Al final muestra la suma total.
"""

var1=int(input("dame un número"))
var2=int(input("dame un número"))
var3=var1+var2
while var3 !=0:
  var1=int(input("dame un número"))
  var2=int(input("dame un número"))
  var3=var1+var2

"""## 4. Contador regresivo
Pide al usuario un número entero positivo y usa un ciclo `while` para imprimir una cuenta regresiva hasta llegar a 0.
"""

# Escribe tu solución aquí

"""## 5. Repetir un mensaje
Pide al usuario un mensaje y un número `n`. Usa un `while` para imprimir ese mensaje `n` veces.
"""

# Escribe tu solución aquí